name: "Hello World workflow"

on: [workflow_dispatch]

jobs:
  run_from_ubuntu_shell:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello from Ubuntu shell!"
  run_from_python_shell:
    runs-on: ubuntu-lates
    steps:
      - run: print("Hello from Python shell!")
        shell: python
  run_from_gh_actions:
    runs-on: ubuntu-latest
    steps:
      uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: "Sergio"
